version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: antoine38660/docker-ce-git-maven
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              jq \
              xmlstarlet
            pip install \
              awscli==1.11.171
      - run:
          name: Set DB variables
          command: |
            xmlfile="/app/src/main/resources/META-INF/persistence.xml"
            xmlcommand="xmlstarlet edit -L -N N='http://xmlns.jcp.org/xml/ns/persistence'"
            xmlcommand -u "//N:property[@name='javax.persistence.jdbc.url']/@value" -v '$DB_URL' xmlfile
            xmlcommand -u "//N:property[@name='javax.persistence.jdbc.user']/@value" -v '$DB_USER' xmlfile
            xmlcommand -u "//N:property[@name='javax.persistence.jdbc.password']/@value" -v '$DB_PASSWORD' xmlfile
      - run:
          name: Build JavaEE application (mvn package)
          command: |
            mvn package
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
            docker tag app $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com/meslocationsvacances:$CIRCLE_SHA1
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            echo "TODO test"
      - deploy:
          name: Deploy application Docker image to AWS
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              /app/deploy.sh
            fi